name: CI

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GAME_VERSION: EMERALD
      GAME_REVISION: 0
      GAME_LANGUAGE: ENGLISH
      MODERN: 0
      COMPARE: 1
    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          submodules: 'recursive'
        env:
          GITHUB_TOKEN: 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


      - name: Checkout agbcc
        uses: actions/checkout@master
        with:
          path: agbcc
          repository: pret/agbcc

      - name: Install binutils
        run: |
          sudo apt install gcc-arm-none-eabi binutils-arm-none-eabi libpng-dev
        # build-essential and git are already installed
        # gcc-arm-none-eabi is only needed for the modern build
        # as an alternative to dkP

      - name: Install agbcc
        run: |
          ./build.sh
          ./install.sh ../
        working-directory: agbcc

      - name: Compare
        run: make -j${nproc} all syms

      - name: Modern
        env:
          MODERN: 1
          COMPARE: 0
        run: make -j${nproc} all

      - name: Move symfiles
        if: ${{ github.event_name == 'push' }}
        run: |
          cp -v *.sym symbols/
          echo "SYMBOLS_COMMIT_MSG=$( git log --format=%s ${GITHUB_SHA} )" >> $GITHUB_ENV

